name = "bdd"
defaultTargets = ["Bdd"]

[leanOptions]
pp.unicode.fun = true

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.23.0-rc2"

[[lean_lib]]
name = "Bdd"

[[lean_exe]]
name = "SatSolver"
